### ISSUE TITLE
GPU enabled docker failure

### ISSUE THREAD

**Issue by alexbooth** [alexbooth/neural-video-generator#6]
Hardware: 2080Ti 11Gb 
Host Os: Ubuntu 20.04

Command (using nvidia-docker2)
```
docker run --gpus all --rm -it -v $PWD/sample_IO:/video_io neural-video-generator python3 exec.py --mode=PROD
```

Got the following error randomly on one run and docker would hang instead of being killed (caused status to be stuck "in progress")
```
python3: /opt/conda/conda-bld/magma-cuda102_1583546904148/work/interface_cuda/interface.cpp:899: void magma_queue_create_from_cuda_internal(magma_device_t, cudaStream_t, cublasHandle_t, cusparseHandle_t, magma_queue**, const char*, const char*, int): Assertion `queue->dBarray__ != __null' failed.
```

Notable that `nvdia-smi` reports more than 100% vmem being used occasionally.

**Comment by alexbooth** [comment]
Testing on EC2 instances with T4 gpu(s) should clear this up

**Comment by alexbooth** [comment]
Not seeing this issue on v100 ec2 instance so far

**Comment by alexbooth** [comment]
Not a problem on v100

**Comment by liangwx** [comment]
which torch version did you use?
